# Generated by Django 2.2.12 on 2020-04-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe", old_name="tag", new_name="tags",
        ),
    ]
